kie接口header 接受 Authorization信息
go-chassis/kie-client pull request #12
Opened 2022-11-08 07:24 UTC by kkf1

2022-11-08 07:55 UTC, little-cui requested changes

2022-11-08 07:55 UTC, little-cui commented on client.go
> +	h.Set(HeaderAuthorization, GetAuthorization(ctx))
如果没有Authorization信息就不用执行Set了

2022-11-08 08:08 UTC, zqfang666 commented on client.go
> +	h.Set(HeaderAuthorization, GetAuthorization(ctx))
已修改

2022-11-09 03:43 UTC, little-cui approved these changes

2022-11-09 06:30 UTC, little-cui commented
kie-client已支持，无需实现，修改pr标题，改成修改门禁错误

2022-11-09 07:17 UTC, merged