correct the format of the error
go-chassis/kie-client pull request #7
Opened 2021-09-24 06:47 UTC by Sphairis

The returned body is an error, format the error for easy obtaining

2021-09-24 08:01 UTC, little-cui requested changes

2021-09-24 08:01 UTC, little-cui commented on client.go
> +	"github.com/go-chassis/cari/pkg/errsvc"
使用goimport格式化

2021-09-24 08:01 UTC, little-cui commented on client.go
> +	return err, formatErr
1. 可以只返回一个err
2. fmt.Errorf(FmtOpFailed, kvID, resp.Status, b)可以放这里

2021-09-24 08:34 UTC, Sphairis commented on client.go
> +	"github.com/go-chassis/cari/pkg/errsvc"
done

2021-09-24 08:35 UTC, Sphairis commented on client.go
> +	return err, formatErr
修改成返回一个，但是这个err := json.Unmarshal(b, formatErr)的err不关注所以返回nil了

2021-09-26 01:17 UTC, tianxiaoliang approved these changes

2021-09-26 01:17 UTC, merged